# Lenguajes de programación

## Lectura

- Python
    - [_Python for Data Analysis_](https://wesmckinney.com/book)
    - [_CS50’s Introduction to Programming with Python_](https://cs50.harvard.edu/python/2022/)
    - [Intro a Python (_Repositorio de cursos de Python del Instituto Humai_)](https://github.com/institutohumai/cursos-python)
    - [Programación en Python (_Repositorio de curso de Python de la UNSAM_)](https://github.com/python-unsam/Programacion_en_Python_UNSAM/tree/master/Notas)
    - [_Real Python_](https://realpython.com/)

- Otros
    - [_R for Data Science_](https://r4ds.had.co.nz/)
    - [_Learning SQL_](https://www.r-5.org/files/books/computers/languages/sql/mysql/Alan_Beaulieu-Learning_SQL-EN.pdf)
    - [_BigQuery SQL Syntax Documentation_](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax)
    - [_Julia Data Science_](https://juliadatascience.io/)
    - [_Observable Tutorials_ (Javascript)](https://observablehq.com/tutorials)

## Actividades

- Utilice el entorno de trabajo previamente instalado y comience a realizar operaciones básicas en cada lenguaje. Esta actividad no tiene una propuesta puntual, pero se sugiere seleccionar algún [dataset](https://drive.google.com/drive/folders/1Lprg5DfAXRnUcmYi5TdzfpKIzQ49ITuq?usp=share_link) y resolver cómo llevar adelante su ingesta en cada herramienta disponible.

## Resumen

Entre las habilidades requeridas para un analista de datos, se destaca en la actualidad el uso de lenguajes de programación. Como se mencionó anteriormente, hasta cierto punto, este rol puede prescindir de los mismos. De hecho, muchas de las actividades que se verán de aquí en adelante pueden resolverse sin recurrir a aquellos. Sin embargo, en pos del crecimiento profesional y el contexto relativo al volumen y complejidad de los datos, los lenguajes de programación resultan esenciales en términos prácticos. Sobre todo si se retoma lo comentado acerca de las cualidades deseadas de un bien realizado análisis de datos (recordar: transparencia, replicabilidad, interoperabilidad y escalabilidad), las cuales los lenguajes pueden abordar sin problema.

En compañia de este libro, se priorizará el uso de Python, aunque puede ser utilizado cualquiera. Sucede en la práctica que algunos lenguajes son referidos para ciertas tareas más que otros. **Python es bastante generalista**, sirve tanto para análisis de datos, para ingeniería y ciencia de datos (las librerías referentes en _machine learning_ están realizadas en python), para usarse como backend en desarrollos web, _web scraping_, entre otras tareas más. Por otro lado, **R se relaciona más al ámbito de la investigación y ciencia**, con sus orígenes en la estadística computacional. **Julia es un lenguaje incipiente**, con un repertorio muy interesante de desarrollos y con la intención de unir lo mejor de Python y R. Y finalmente, **Javascript**, que al igual que python se utiliza en diferentes ámbitos, incluso más, pero en análisis de datos se puede considerar **una muy buena herramienta especialmente para visualización de datos**.

SQL merece mención aparte porque, en lo respecta a uso de bases de datos (para el almacenamiento y consulta de datos), es la norma. Es decir, es inevitable su uso y cualquier búsqueda laboral para roles de análisis de datos es probable que lo señalen como un requisito excluyente. Para este lenguaje pueden encontrarse diferentes implementaciones según la empresa/organización que promueva su propia base de datos. Suelen todos tener una base común y luego un set de funciones / syntaxis particular, que se adquiere rápidamente con la práctica.