# Origen y recolección de datos

## Lectura

- [Origen de los datos (_Estadística para Todos_: pág. 51 y 52)](https://drive.google.com/file/d/1oe0BDy9U1l-H54Ry_mkVC5hxGE-Z5rGm/view?usp=share_link)
- [Muestreo (_Estadística para Todos_: pág. 29 a 35)](https://drive.google.com/file/d/1oe0BDy9U1l-H54Ry_mkVC5hxGE-Z5rGm/view?usp=share_link)
- [Fuentes de datos (_Estadística Aplicada a las Ciencias Sociales y Humanas_: pág. 18 a 20)](https://drive.google.com/file/d/1rayM3pmKjnPR8BvKyU8ZGDo8o_2ZuPZR/view?usp=share_link)
- [Métodos de muestreo (_Estadística Aplicada a los Negocios y la Economía_: pág. 266 a 268)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=share_link)
- [Muestras aleatorias (_Probabilidad y Estadística | Aplicaciones y Métodos_: pág. 214 a 217)](https://drive.google.com/file/d/1VCLbf-N79MIcStIe35XzL5NF-DTGENo_/view?usp=share_link)
- [Métodos de recolección de datos para una investigación](https://drive.google.com/file/d/137b6XkFVYO_bT3jBDMTlPivu97vLftoR/view?usp=share_link)
        
## Actividades

- Considere el dataset [Pokemon](https://drive.google.com/drive/folders/1Lprg5DfAXRnUcmYi5TdzfpKIzQ49ITuq?usp=share_link). Lleve adelante la descripción de 2 variables numéricas (cálculo de media y desvío estándar) y 2 categóricas (cálculo de alguna proporción de interés). Luego extraiga una serie de muestras bajo algún criterio que le resulte adecuado. Vuelva a calcular los valores anteriores, compare y extraiga conclusiones.

## Resumen

El origen y recolección de los datos determina las conclusiones que pueden extraerse de los mismos. Tener un **censo** (un relevamiento completo de las unidades de análisis) no será lo mismo que tener una **muestra** (un relevamiento parcial); la segunda lleva consigo la **incertidumbre propia de no contar con todos los datos**. Pero justamente será ese el escenario donde el análisis de datos estará más presente. 

Una muestra será habitualmente la opción más viable para conseguir datos. Incluso en la era del _big data_, por más datos que se tengan, suelen ser representaciones parciales de la realidad, de los procesos que los generan. La muestra es la regla, no la excepción.

Es un procedimiento mediante el cual **se extrae, de forma aleatoria, una serie de unidades de análisis de un conjunto mayor (finito o infinito) de unidades**. En su versión más simple, consiste en extraerlas directamente, aunque ésta puede no ser la mejor forma de hacerlo. Más adelante se verán otras metodologías que, en esencia, buscan mejorar la **representatividad de los datos obtenidos** respecto del conjunto total, o lo que es igual, disminuir los **errores debidos al muestreo mismo**. La aleatoriedad juega aquí un rol fundamental, siendo el canal por el cual se busca eliminar todo otro tipo de **errores debido a la subjetividad**, mientras que además se debe evitar otros **errores por cuestiones operacionales**. Cabe señalar además que la muestra no es solamente una técnica aplicada a datos que son _reales_, sino que se pueden obtener a partir de una simulación o _datos sintéticos_, lo cual será útil para la experimentación.

Un muestreo (de acá en adelante siempre entendido como aleatorio) dará como resultado variables necesariamente aleatorias; el objetivo será caracterizarlas, pero teniendo en cuenta su naturaleza azarosa. Porque **cada vez que se tome una muestra, los resultados de un promedio o una desviación estándar (u otra medida) para determinada variable, serán distintos**. Todas y cada una de las veces, siempre será distinto. Estos resultados en sí, pueden asimismo considerarse nuevas variables y también caracterizarse. Justamente este es uno de los grandes pilares del análisis de datos.

Recapitulando, lo que será de interés de aquí en adelante, es la capacidad de lidiar con una muestra y obtener conclusiones de las variables a partir de la misma. En el siguiente capítulo, se hará una introducción a la teoría y conceptos de probabilidad, que serán de gran ayuda.