# Estimación puntual y por intervalos de confianza

#### Lectura

- [Estimación y parámetros (_Estadística para Todos_: pág. 55)](https://drive.google.com/file/d/1oe0BDy9U1l-H54Ry_mkVC5hxGE-Z5rGm/view?usp=share_link)
- [Variabilidad entre muestra y muestra (_Estadística para Todos_: pág. 58 a 63)](https://drive.google.com/file/d/1oe0BDy9U1l-H54Ry_mkVC5hxGE-Z5rGm/view?usp=share_link)
- [Teorema Central del Límite (_Estadística para Todos_: pág. 200 a 207)](https://drive.google.com/file/d/1oe0BDy9U1l-H54Ry_mkVC5hxGE-Z5rGm/view?usp=share_link)
- [Distribuciones de muestreo de estadísticas (_Probabilidad y Estadística | Aplicaciones y Métodos_: pág. 218 a 238)](https://drive.google.com/file/d/1VCLbf-N79MIcStIe35XzL5NF-DTGENo_/view?usp=share_link)
- [Estimación por intervalos (_Estadística para Todos_: pág. 214 a 228)](https://drive.google.com/file/d/1oe0BDy9U1l-H54Ry_mkVC5hxGE-Z5rGm/view?usp=share_link)
- [Estimación e intervalos de confianza (_Estadística Aplicada a los Negocios y la Economía_: pág. 297 a 315)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=share_link)
- [Propiedades deseables de los estimadores puntuales (_Probabilidad y Estadística | Aplicaciones y Métodos_: pág. 251 a 261)](https://drive.google.com/file/d/1VCLbf-N79MIcStIe35XzL5NF-DTGENo_/view?usp=share_link)
- [Confidence Intervales (_STAT 500 | Applied Statistics_: lesson 5)](https://online.stat.psu.edu/stat500/lesson/5)
    
#### Actividades

- Considere el dataset [Pokemon](https://drive.google.com/drive/folders/1Lprg5DfAXRnUcmYi5TdzfpKIzQ49ITuq?usp=share_link) y asuma que es el listado completo de todos los pokemones (es decir, la población). Use los parámetros obtenidos previamente y vuelva a calcular estimadores (utilizando las fórmulas adecuadas para cada caso, vistas en esta sección) pero realizando muestras aleatorias de manera sucesiva. Realice este mismo procedimiento con muestras de diferente tamaño. Grafique la distribución de los estimadores y saque conclusiones.
- Retome lo realizado en la anterior clase y estime nuevamente los valores de media, varianza y proporción para las variables seleccionadas, utilizando diferentes niveles de confianza. Escriba una breve reseña con conclusiones acerca de los resultados obtenidos.

#### Resumen

Estimar es aproximar. Siendo que no se dispone, por razones operacionales o conceptuales, de toda la información disponible, habrá inevitablemente ciertas características de las variables que serán desconocidas; éstas pueden ser cualquiera de las medidas de posición, dispersión o relación vistas previamente. El verdadero valor de éstas es lo que recibirá el nombre de **parámetro**. 

El objetivo será justamente aproximarse a estos parámetros a través de diferentes fórmulas, que reciben el nombre de **estimadores**. Para cada caso, no hay único estimador posible, aunque hay algunos que cumplirán con **ciertas propiedades que los hacen óptimos** o al menos mejores en comparación a otros.

Para llegar a un valor aproximado de los parámetros, a través de los estimadores, serán necesario datos. Aquí entra en juego el proceso de muestreo, la **obtención de datos, necesariamente aleatoria,** para que la estimación arroje resultados válidos. Mientras mayor y más representativa sea una muestra respecto de la población, los valores de los estimadores estarán cada vez más cerca de los valores de los parámetros, siempre siendo distintos en cada muestra pero con una variación menor a medida que el tamaño de muestra tienda al número completo de unidades de análisis (o al infinito).

La **variación en el resultado de los estimadores** jugará un rol fundamental en la gestión de la incertidumbre. Es habitual no definir un valor tal para el estimador, sino más bien un **intervalo**. Se podrá decir que dicho intervalo, con cierto grado de confianza, contendrá al verdadero valor del parámetro en una cantidad de veces determinada (cantidad de muestras o de experimentos).

Todos los resultados obtenidos serán sujetos al **supuesto de que la población (de unidades de anális) tiene determinada distribución**. Al intentar obtener una estimación de la media, de la varianza o una proporción, se deberá tener en cuenta que justamente son parámetros utilizados en distribuciones particulares, algunas de las vistas anteriormente, como la normal o binomial. Eso, en cierta forma, facilitará los cálculos y dará mayor certidumbre respecto de las conclusiones; pero, en muchos casos, las distribuciones no son conocidas o bien no se intentará estimar algunos de estos parámetros. En ese caso, se estará frente a la necesidad de recurrir a **métodos no paramétricos de estimación**, los cuales se verán más adelante.


