# Probabilidad aplicada

## Lectura

- [Epílogo: Estadística y Probabilidad (_Estadística para Todos_: pág. 245 a 247)](https://drive.google.com/file/d/1oe0BDy9U1l-H54Ry_mkVC5hxGE-Z5rGm/view?usp=share_link)
- [Estudio de los conceptos de la probabilidad (_Estadística Aplicada a los Negocios y la Economía_: pág. 144 a 151)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=share_link)
- [Distribuciones de Probabilidad Discreta (_Estadística Aplicada a los Negocios y la Economía_: pág. 186 a 202)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=share_link)
- [Distribuciones de Probabilidad Continua (_Estadística Aplicada a los Negocios y la Economía_: pág. 222 a 242)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=share_link)
- [Probability (_STAT 500 | Applied Statistics_: lesson 2)](https://online.stat.psu.edu/stat500/lesson/2)
- [Probability Distributions (_STAT 500 | Applied Statistics_: lesson 3)](https://online.stat.psu.edu/stat500/lesson/3)
- [Sampling Distributions (_STAT 500 | Applied Statistics_: lesson 4)](https://online.stat.psu.edu/stat500/lesson/4)
- [Introducción a conceptos de probabilidad y estadística descriptiva (_Laboratorio de Datos – 1er Cuatrimestre 2021: Clase 4_)](http://materias.df.uba.ar/lda2021c1/171-2/)
    
## Actividades 

- Considere el dataset [Pokemon](https://drive.google.com/drive/folders/1Lprg5DfAXRnUcmYi5TdzfpKIzQ49ITuq?usp=share_link). Proponga 3 experimentos sobre dicha población para obtener como resultado una variable aleatoria cuya distribución sea: (1) binomial, (2) normal y (3) chi cuadrado.
- Responda las siguientes preguntas:
    - ¿Cuál es la probabilidad de obtener un pokemon cuya velocidad sea mayor a 100?
    - ¿Cuál es la probabilidad de obtener un pokemon cuyo ataque sea igual a 60?
    - ¿Cuál es la probabilidad de obtener un pokemon de aire al realizar una muestra aleatoria de 10 pokemones?
    - ¿Cuál es la probabilidad de obtener un pokemon de generación 3 al seleccionar un sólo pokemon?
    - Dado que un pokemon es de tierra, ¿cuál es la probabilidad que su defensa sea menor a 50?
    - ¿Cuál es la probabilidad de obtener un pokemon de tierra y con defensa menor a 50?
    - ¿Cuál es la probabilidad de que un pokemon sea de tierra suponiendo que en una muestra de 10 unidades obtuvo sólo 1 pokemon de este tipo? 
    
## Resumen

La probabilidad es una herramienta fundamental para el análisis de datos, no tanto por su uso directo, sino porque **es el sustento matemático de muchas demostraciones de procesos y fórmulas que habitualmente se aplican**. Por tanto, conocer los conceptos y definiciones básicos es una puerta a comprender mejor tanto el análisis como las conclusiones obtenidas.

Será particularmente útil asimilar las distribuciones más relevantes que surgen como resultado del análisis de variables aleatorias; éstas son: **la distribución binomial, la distribución normal y la distribución chi-cuadrado**. Cada una estará asociada al estudio de medidas de posición, dispersión y relación, vistas anteriormente. Es decir, estas medidas, si se dan las adecuadas condiciones, tendrán un **comportamiento teóricamente definido y demostrado**, lo cual posibilita enormemente su análisis. También será útil el conocimiento y cálculo de **probabilidades conjuntas y condicionales**, habituales en el análisis multivariado.