# Técnicas de muestreo

#### Lectura

- [Métodos de muestreo (_Estadística Aplicada a los Negocios y la Economía_: pág. 266 a 271)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=share_link)
- [Elección del tamaño adecuado de una muestra (_Estadística Aplicada a los Negocios y la Economía_: pág. 316 a 321)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=share_link)
- [Estimating Population Mean and Total under SRS (_STAT 506 | Sampling Theory and Methods_: lesson 1)](https://online.stat.psu.edu/stat506/lesson/1)
- [Confidence Intervals and Sample Size (_STAT 506 | Sampling Theory and Methods_: lesson 2)](https://online.stat.psu.edu/stat506/lesson/2)
- [Stratified Sampling (_STAT 506 | Sampling Theory and Methods_: lesson 6)](https://online.stat.psu.edu/stat506/lesson/6)
- [Cluster and Systematic Sampling (_STAT 506 | Sampling Theory and Methods_: lessons 7 y 8)](https://online.stat.psu.edu/stat506/lesson/7)
- [Multi-Stage Designs (_STAT 506 | Sampling Theory and Methods_: lesson 9)](https://online.stat.psu.edu/stat506/lesson/9)

#### Actividades

- Considere el dataset [LinkedIn Freelancer Survey Results](https://drive.google.com/drive/folders/1Lprg5DfAXRnUcmYi5TdzfpKIzQ49ITuq?usp=share_link). Señale algunos aspectos claves a considerar en la realización de dicha encuesta (¿acaso podría implementarse un muestreo estratificado, por conglomerados o sistemático?) y haga una estimación del tamaño adecuado para la misma.
- Considere el dataset [London Bike Sharing Dataset](https://drive.google.com/drive/folders/1Lprg5DfAXRnUcmYi5TdzfpKIzQ49ITuq?usp=share_link). Asuma que es el total de registros por hora de viajes en bicicleta hasta el día de la fecha. Realice un análisis exploratorio de la variable _cnt_ (total de viajes), principalmente calculando la media y desvío estándar. Luego, implemente un muestreo sistemático de los datos, estime los paramétros correspondientes y compare. Realice la comparación considerando temporada (_season_) y fines de semana (_weekend_).