# Técnicas de muestreo

## Lectura

- [Métodos de muestreo (_Estadística Aplicada a los Negocios y la Economía_: pág. 266 a 271)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=share_link)
- [Elección del tamaño adecuado de una muestra (_Estadística Aplicada a los Negocios y la Economía_: pág. 316 a 321)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=share_link)
- [Estimating Population Mean and Total under SRS (_STAT 506 | Sampling Theory and Methods_: lesson 1)](https://online.stat.psu.edu/stat506/lesson/1)
- [Confidence Intervals and Sample Size (_STAT 506 | Sampling Theory and Methods_: lesson 2)](https://online.stat.psu.edu/stat506/lesson/2)
- [Stratified Sampling (_STAT 506 | Sampling Theory and Methods_: lesson 6)](https://online.stat.psu.edu/stat506/lesson/6)
- [Cluster and Systematic Sampling (_STAT 506 | Sampling Theory and Methods_: lessons 7 y 8)](https://online.stat.psu.edu/stat506/lesson/7)
- [Multi-Stage Designs (_STAT 506 | Sampling Theory and Methods_: lesson 9)](https://online.stat.psu.edu/stat506/lesson/9)

## Actividades

- Considere el dataset [LinkedIn Freelancer Survey Results](https://drive.google.com/drive/folders/1Lprg5DfAXRnUcmYi5TdzfpKIzQ49ITuq?usp=share_link). Señale algunos aspectos claves a considerar en la realización de dicha encuesta (¿acaso podría implementarse un muestreo estratificado, por conglomerados o sistemático?) y haga una estimación del tamaño adecuado para la misma.
- Considere el dataset [London Bike Sharing Dataset](https://drive.google.com/drive/folders/1Lprg5DfAXRnUcmYi5TdzfpKIzQ49ITuq?usp=share_link). Asuma que es el total de registros (por hora) de viajes en bicicleta hasta el día de la fecha. Realice un análisis exploratorio de la variable _cnt_ (total de viajes), principalmente calculando la media y desvío estándar. Luego, implemente un muestreo sistemático de los datos, estime los paramétros correspondientes y compare. Realice dicha comparación en base a temporada (_season_) y fines de semana (_weekend_).

## Resumen

Las situaciones reales para la obtención de datos dificilmente permiten que un muestreo aleatorio simple sea llevado adelante. Por ejemplo, cuestiones como los **costos operacionales** debido a la extensión de territorio son comunes en cualquier estudio de estadísticas sociales. Es así que han surgido diferentes técnicas de muestreo y estimadores asociadas a las mismas, de tal manera que la aproximación a los parámetros reales de la población sea la mejor (que es el objetivo de cualquier estimador).

Dicho eso, hay una consideración inicial muy importante al comenzar el muestreo: el **tamaño de la muestra**. Si es muy pequeño, la representatividad podría no ser adecuada (con todo lo que ello implica y que se ha señalado anteriormente); si es muy grande, es esencialmente gasto innecesario de recursos. Por tanto, determinar un adecuado tamaño de muestra es el puntapié para un buen análisis de datos, que estará atado luego a la técnica con la cual se realiza el muestreo. 

En ese sentido, hay 2 que recursos que destacan: el uso de **estratos** y el uso de **conglomerados**.

Los primeros (estratos) están pensados para estudiar _regiones_ o agrupamientos de interés para la investigación, obteniendo estadísticas no sólo a nivel general sino al interior de cada uno. Es una división que puede realizarse sobre la población (el conjunto total de unidades de análisis) antes o después del muestreo (post estratificación), con la condición de estudiar el conjunto completo de estratos, ya que posiblemente cada estrato sea una representación parcial de la población. Sobre cada estrato se realiza una muestra aleatoria que luego se estudia en conjunto con el resto. Un ejemplo de estratos pueden ser los barrios de una ciudad.

Los segundos (conglomerados) son agrupamientos de unidades de análisis que suelen presentarse naturalmente juntos y que cuentan con la particularidad de ser representaciones de la población por sí mismos, así como también de facilitar el estudio / muestreo. Los conglomerados no se muestrean, sino que se relevan todas las unidades al interior de los mismos. La unidad de muestreo es entonces el conglomerado, siendo éstos los que se seleccionan, habitualmente de forma sistemática. Un ejemplo de conglomerados podrían ser los pasajeros de un vuelo.