# ANOVA: Análisis de la varianza

## Lectura

- [Análisis de la varianza (_Estadística Aplicada a los Negocios y la Economía_: pág. 410 a 440)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=share_link)
- [Introduction to ANOVA (_STAT 500 | Applied Statistics_: lesson 10)](https://online.stat.psu.edu/stat500/lesson/10)

## Actividades

- Considere el dataset [CNC turning Experiment](https://drive.google.com/drive/folders/1Lprg5DfAXRnUcmYi5TdzfpKIzQ49ITuq?usp=share_link). Identifique aquellos factores para los cuales la media de la fuerza (_force_), en al menos un grupo, sea significativamente diferente. Evalué en todos los casos los supuestos del análisis. Si para un grupo de factores encuentra diferencias, determine entre cuáles. Concluya cuáles factores son los que determinan la mayor fuerza posible alcanzada.
- Lleve adelante una transformación de los datos tal que las réplicas de cada corrida (_run_id_) pasen a conformar las columnas r1 a r6 y además calcule la media y desvío estándar asociadas a las mismas.

## Resumen

En la práctica, la comparación de promedios (a través de pruebas estadísticas) suele implicar **más de dos categorías, grupos y/o variables**. Consideren, por ejemplo, un experimento con 6 diferentes tratamientos, el resultado de cada uno de ellos variará, en mayor o menor medida, y como investigador se intentará conocer esa **variación**, concluyendo si uno o más son realmente diferentes al resto en cuanto a sus efectos. Justamente, el análisis de dicha variación es lo que se conoce como ANOVA (análisis de la varianza).

Esta técnica es muy simple en esencia. Se compara la **variación dentro de cada grupo**, respecto a la **variación entre grupos**. Si la última es _considerablemente_ grande (y la primera considerablemente chica) se estará en condiciones de decir que los grupos son diferentes. Dicho eso, según se quiera poner a prueba diferentes variables (factores) que afectan el resultado, el ANOVA como tal puede llegar a ser bastante complejo. Sea cual fuere el escenario, es muy importante tener presente qué es lo que implicará la introducción como tal de más componentes al análisis, consideración clave para obtener conclusiones válidas. Un caso importante en ese aspecto es el uso de **factores de bloqueo**, los cuales serán instrumentaciones del experimento realizadas a propósito para controlar la variación de la respuesta.

Posteriormente a las conclusiones del ANOVA, suelen darse otros **procedimientos para específicamente conocer cuál tratamiento / grupo es diferente al resto**. Esto es lo que se conoce como análisis _post hoc_.

ANOVA, siendo una prueba estadística, es un procedimiento muy utilizado en investigación científica; pero es destacable que no debe vérselo simplemente como un test sino como una forma de **estimar una variable continua en función de una o más variables categóricas**, lo que se denomina, en términos generales, como una _regresión_ (tema que se verá en el próximo capítulo). También es importante señalar que el análisis de la varianza, tal como se presenta aquí, es un **método paramétrico**, teniendo su contrapartida no paramétrica para el caso donde no se cumplan los supuestos (o bien se investigue otro parámetro que no sea el promedio).

