# KNN y CART

#### Lectura

- [Relación entre variables (_Estadística para Todos_: pág. 168 a 196)](https://drive.google.com/file/d/1oe0BDy9U1l-H54Ry_mkVC5hxGE-Z5rGm/view?usp=share_link)
- [El estudio de la relación entre variables (_Estadística Aplicada a las Ciencias Sociales y Humanas_: pág. 105 a 130)](https://drive.google.com/file/d/1rayM3pmKjnPR8BvKyU8ZGDo8o_2ZuPZR/view?usp=share_link)
- [Regresión lineal y correlación (_Estadística Aplicada a los Negocios y la Economía_: pág. 461 a 494)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=share_link)
- [Análisis de regresión: el modelo lineal simple (_Probabilidad y Estadística | Aplicaciones y Métodos_: pág. 443 a 478)](https://drive.google.com/file/d/1VCLbf-N79MIcStIe35XzL5NF-DTGENo_/view?usp=share_link)
- [Fundamentals of Data Visualization (Part I: Cap. 12)](https://clauswilke.com/dataviz)
- [Linear Regression Foundations (_STAT 500 | Applied Statistics_: lesson 9)](https://online.stat.psu.edu/stat500/lesson/9)
- [Introduction to Modeling Libraries in Python (_Python for Data Analysis_: cap. 12)](https://wesmckinney.com/book/modeling.html)
- [In Depth: Linear Regression (Python Data Science Handbook)](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/05.06-Linear-Regression.ipynb)

#### Actividades
- Considere el dataset [CNC turning Experiment](https://drive.google.com/drive/folders/1Lprg5DfAXRnUcmYi5TdzfpKIzQ49ITuq?usp=share_link). Identifique aquellos factores para los cuales la media de la fuerza (_force_), en al menos un grupo, sea significativamente diferente. Evalué en todos los casos los supuestos del análisis. Si para un grupo de factores encuentra diferencias, determine entre cuáles. Concluya cuáles factores son los que determinan la mayor fuerza posible alcanzada.
- Lleve adelante una transformación de los datos tal que las réplicas de cada corrida (_run_id_) pasen a conformar las columnas r1 a r6 y además calcule la media y desvío estándar asociadas a las mismas.