project:
  type: book
  output-dir: docs
  preview:
    host: 0.0.0.0
    port: 4200
    browser: false

book:
  title: "An치lisis de datos"
  author: "Ervin Wilneder"
  date: "1/18/2023"
  chapters:
    - index.qmd
    - part: "Fundamentos"
      chapters:
        - 01 - conceptos y definiciones.qmd
        - 02 - entorno de trabajo.qmd
        - 03 - lenguajes de programaci칩n.qmd
        - 04 - datos unidades y variables.qmd
    - part: "An치lisis exploratorio"
      chapters:
        - 05 - tablas de frecuencias.qmd
        - 06 - descripcion de variables.qmd
        - 07 - visualizacion.qmd
    - part: "An치lisis inferencial"
      chapters:
        - 08 - origen y recoleccion.qmd
        - 09 - manipulacion de datos.qmd
        - 10 - probabilidad aplicada.qmd
        - 11 - estimacion puntual y por intervalos.qmd
        - 12 - tests de hipotesis.qmd
        - 13 - estadistica no parametrica.qmd
        - 14 - tecnicas de muestreo.qmd
        - 15 - anova.qmd
        - 16 - regresion lineal.qmd
        - 17 - regresion logistica.qmd
        - 18 - knn y cart.qmd
    # - part: "Machine Learning"
    # - part: "DataOps / MLOps"
  page-navigation: true

format:
  html:
    theme: default
    fontcolor: "#373a3c"
    fontsize: 0.95em
    linestretch: 1.7
    mainfont: "Open Sans"
    number-sections: false
    page-layout: article