# Conceptos y definiciones

#### Lectura

- <https://aws.amazon.com/es/what-is/data-analytics/>
- <https://www.intel.la/content/www/xl/es/artificial-intelligence/what-is-data-analytics.html>
- <https://www.oracle.com/business-analytics/data-analytics/>

#### Actividades
- ¿Qué es _Data Analytics_? ¿Considera que es lo mismo que _Análisis de Datos_?
- ¿En qué se diferencia de _Big Data Analytics_?
- ¿Cuáles son los pasos a seguir en un proceso de análisis de datos?
- Mencione al menos 3 herramientas vinculadas al análisis de datos
- ¿Qué tipo de análisis de datos se pueden hacer?
- Relacione la anterior respuesta con los siguientes conceptos: _raw data_, _information_, _knowledge_, _insight_, _actionable insight_, _decision-making_, _model_
- Diferencie brevemente _Machine Learning_, _Data Mining_, _Data Science_, _Business Intelligence_, _Data Analysis_ y _Data Analytics_

#### Resumen

El análisis de datos es una actividad que se encuentra integrada a otras como **ingeniería y ciencia de datos** compartiendo conceptos y herramientas, y habitualmente superponiéndose en el día a día de muchas organizaciones. Por esto mismo, como profesional del área, es importante reconocer cuáles son las **incumbencias del análisis de datos** y cómo se relaciona con el resto del **ciclo de vida de los datos**. 

Surge entonces la necesidad de definir y comprender conceptos fundamentales para lograr esa distinción. Como suele suceder en otros rubros, varios de estos conceptos son asimilados del inglés y se utilizan diariamente de esta manera, lo que contribuye a la confunsión en algunos casos. Además, las definiciones no siempre son unísonas: dependen de cada autor y evolucionan en el tiempo. Implica así una **capacitación, actualización y reflexión constante**.

Como actividad, el análisis de datos requiere principalmente **conocimientos de estadística y de dominio** (o de negocio), de tal manera de poder trabajar los datos, **obtener conclusiones** y traducir esas conclusiones en **recomendaciones o acciones** (o simplemente **producir información / conocimiento** para su posterior tratamiento). 

El rol no necesariamente implica el uso de **lenguajes de programación**, aunque (en el estadío actual del área) suele ser altamente recomendable adquirir su uso. De no contar con ello, es esencial la experiencia en al menos una **herramienta de visualización** (Tableau, PowerBI, Looker) y uso avanzado de **planillas de cálculo** (Excel, Google Sheets).

Retomando lo dicho, es habitual también la necesidad de un cierto grado de **transformación de los datos**. En ese aspecto, **Python, R y SQL** son herramientas de gran ayuda, que desde ya pueden utilizarse más adelante en el análisis como tal. De hecho, su uso se ha consolidado cada vez más de forma mandatoria en términos de poder trabajar con **grandes volúmenes de datos** y elaborar **modelos complejos**, inviables de implementar con otras herramientas como las mencionadas anteriormente.

Posteriormente al análisis, la presentación de los mismos es sumamente importante, y es incluso un diferencial. En ese sentido, un analista de datos completo cuenta con la **capacidad para la elaboración de informes y visualizaciones**, pudiendo abstraerse de la parte técnica y mostrar efectivamente y de manera sencilla los resultados de su análisis.

Recapitulando, el análisis de datos pasa a ser hoy un conjunto de conocimientos y técnicas que, con las herramientas adecuadas y enmarcado correctamente en un **proceso de analítica de datos**, permite la **toma de decisiones** dentro de las organizaciones a través de la **exploración e inferencia de los datos**.