# Datos, unidades y variables de análisis

## Lectura

- [Los Datos (_Estadística Aplicada a las Ciencias Sociales y Humanas_: pág. 13 a 15)](https://drive.google.com/file/d/1rayM3pmKjnPR8BvKyU8ZGDo8o_2ZuPZR/view?usp=share_link)
- [Las Variables (_Estadística Aplicada a las Ciencias Sociales y Humanas_: pág. 15 a 17)](https://drive.google.com/file/d/1rayM3pmKjnPR8BvKyU8ZGDo8o_2ZuPZR/view?usp=share_link)
- [La Primera Organización de los Datos: la matriz de datos (_Estadística Aplicada a las Ciencias Sociales y Humanas_: pág. 25 a 27)](https://drive.google.com/file/d/1rayM3pmKjnPR8BvKyU8ZGDo8o_2ZuPZR/view?usp=share_link)
- [Tipos de variables (_Estadística Aplicada a los Negocios y la Economía_: pág. 8 y 9)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=share_link)
- [Variables aleatorias (_Estadística Aplicada a los Negocios y la Economía_: pág. 189 y 190)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=share_link)
- [Types of Data (_STAT 414 | Introduction to Probability Theory_: lesson 1.4)](https://online.stat.psu.edu/stat414/lesson/1/1.4)
- [El concepto de variable aleatoria (_Probabilidad y Estadística | Aplicaciones y Métodos_: pág. 52 y 53)](https://drive.google.com/file/d/1VCLbf-N79MIcStIe35XzL5NF-DTGENo_/view?usp=share_link)

## Actividades

- Busque y analice algún artículo que hable acerca de la diferencia entre datos, información y conocimiento. Provea un ejemplo propio que muestre dicha diferencia.
- Considere el dataset [Top Trends on TikTok & YoutubeShorts](https://drive.google.com/drive/folders/1Lprg5DfAXRnUcmYi5TdzfpKIzQ49ITuq?usp=share_link). Determine la unidad de análisis, las variables y su tipo. ¿Es alguna de ellas aleatoria?

## Resumen

**Los datos** son el insumo básico para el análisis de datos. La **mínima unidad de información**, la materia prima a partir de la cual se produce **conocimiento** y se pueden tomar acciones basadas en evidencia con cierto **grado medible de incertidumbre**. 

Es adecuado pensar a un dato como aquello que puede colocarse dentro de una celda (de una planilla); esto es, un número, una letra, una palabra, un verdadero o falso. El hecho de considerar a _algo_ como un dato dependerá del análisis mismo, porque ese dato surgirá como resultado del entrecruzamiento de 2 conceptos sumamente importantes: **la unidad de análisis y la variable**.

La unidad de análisis es el **objeto o sujeto** sobre el cual se lleva adelante el análisis. La variable es la **característica de interés** de ese objeto o sujeto, sobre el cual se observará o medirá un dato. La primera suele identificarse como cada una de las filas (de una planilla), la segunda como las columnas (ver imagen); aunque no siempre tiene por qué ser así. Entonces, la secuencia inicial de cualquier análisis de datos será **identificar la unidad de análisis, la o las variables de estudio y obtener de estas variables uno o más datos**. 

|          | variable 1 | variable 2 | variable 3 |
|----------|:----------:|:----------:|:----------:|
| unidad 1 |   dato     |    dato    |   dato     |
| unidad 2 |   dato     |    dato    |   dato     |
| unidad 3 |   dato     |    dato    |   dato     |

Las variables pueden ser de 2 tipos: **cuantitativas o cualitativas**. Las primeras, asimismo, pueden ser continuas o discretas, y las segundas, ordinales o nominales. Lo importante de reconocer qué tipo de variable se tiene a la mano está en el hecho de **anticipar las técnicas y limitaciones o no para cada caso**. Las variables más flexibles y potentes son las cuantitativas continuas porque las mismas pueden discretizarse, ordenarse o transformarse en cualitativas, no así al revés.

Por otra parte, la clasificación de variables puede implicar no sólo su tipo, sino también **si es resultado o no de un proceso aleatorio**. Es decir, si es producto del azar en algún punto de su obtención. Esto traerá apareado un cambio completo en el modo de analizar a la variable, así como también de las conclusiones que pueden extraerse.

Recapitulando, como analista de datos, es sumamente importante participar o tener conocimiento pleno en la definición exhaustiva de la unidad de análisis, del recocimiento de las variables y de la obtención de datos, ya que estos 3 puntos son la base sobre la cual se construye por completo cualquier análisis.