# Tablas de frecuencias

#### Lectura

- [Construcción de una tabla de frecuencias (_Estadística Aplicada a los Negocios y la Economía_: pág. 23 y 24)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=sharing)
- [Construcción de distribuciones de frecuencias: datos cuantitativos (_Estadística Aplicada a los Negocios y la Economía_: pág. 29 a 34)](https://drive.google.com/file/d/1FX-LDq_MY3dD6UkhpktQVN6iDgNKug0N/view?usp=sharing)
- [Problema de Trabajo e Investigación Estadística (_Estadística Aplicada a las Ciencias Sociales y Humanas_: pág. 12 y 13)](https://drive.google.com/file/d/1rayM3pmKjnPR8BvKyU8ZGDo8o_2ZuPZR/view?usp=share_link)
- [El Análisis de la Matriz de Datos (_Estadística Aplicada a las Ciencias Sociales y Humanas_: pág. 28)](https://drive.google.com/file/d/1rayM3pmKjnPR8BvKyU8ZGDo8o_2ZuPZR/view?usp=share_link)
- [Las Distribuciones de Frecuencias en el Análisis Univariado (_Estadística Aplicada a las Ciencias Sociales y Humanas_: pág. 29 a 45)](https://drive.google.com/file/d/1rayM3pmKjnPR8BvKyU8ZGDo8o_2ZuPZR/view?usp=share_link)

#### Actividades
- Considere el set de datos [Top Trends on TikTok & YoutubeShorts](https://drive.google.com/drive/folders/1Lprg5DfAXRnUcmYi5TdzfpKIzQ49ITuq?usp=share_link). Elabore tablas de frecuencias absolutas, relativas y acumuladas (si corresponde) para todas las variables.
- Releve el uso e implementación de _tablas pivote_ en diferentes softwares/plataformas (ej: Excel, Google Sheets, Python, R, entre otros). Utilice alguno de los ejemplos sugeridos para realizar las anteriores tablas.
- Elabore al menos 3 preguntas de negocio que podrían ser respondidas con las anteriores tablas.

#### Resumen

La forma más básica de analizar / resumir un conjunto de datos es una tabla de frecuencias. Implica la **operación de conteo de unidades de análisis o de sus variables, agrupadas por algún criterio, conformando categorías o clases excluyentes (sin solapamiento)**. En las variables cualtitativas, suele ser bastante directo, siendo que las categorías se encuentran naturalmente identificadas; en las cuantitativas dependerá del análisis, pudiendo **agrupar por intervalos del mismo o diferente tamaño**, según se necesite.

El resultado puntual del conteo para cada clase o intervalo se denomina _frecuencia_ y el conjunto de éstas se conoce como _distribución de frecuencias_. La frecuencia puede ser _absoluta_ o _relativa_ (si es que se divide por el total de unidades o total de la variable), dando una mejor idea de cuán _relevante_ es cierta clase respecto del total y además permitiendo comparar con otras variables. La suma de la columna con las frecuencias absolutas debe dar siempre como resultado el conteo de unidades total, mientras que la relativa debe dar siempre 1.

Así, la tabla de frecuencias puede construirse inicialmente de la siguiente manera: una columna con las clases / categorías / intervalos, una columna con las frecuencias absolutas y otra columna con las relativas. Éstas 2 últimas suelen acompañarse de una fila con el total, de tal manera de verificar lo anteriormente dicho. Por sobre esta configuración básica, se puede agregar una columna con el punto medio de clase (habitualmente la diferencia entre valor máximo y mínimo de un intervalo, dividido 2) o punto máximo, lo cual ayuda a identifar rápidamente un intervalo sin recurrir a su definición por intervalo (ambos máximo y mínimo), y también siendo soporte para una posterior visualización. Adicionalmente, también puede utilizarse otra columna con el ancho de clase ó amplitud (diferencia entre valor máximo y mínimo).

Para responder algunas **preguntas del análisis** puede llegar a ser necesario el cálculo además de **frecuencias acumuladas** (esto únicamente para variables susceptibles de ordenamiento). Esencialmente, una vez ordenada la tabla por algún criterio, se procede a la suma fila por fila de las frecuencias absolutas y/o relativas. Sobre estas nuevas columnas no tiene sentido realizar una suma, pero sí se debe constatar que el resultado de la última fila sumada dé el total de la frecuencia absoluta o relativa, según se haya utilizada una u otra.

Pudiendo realizarse de forma manual, en conjuntos grandes de datos, es posible recurrir al uso de _tablas pivote_ o alguna implementación específica para tablas de frecuencia (ej: [función FREQUENCY en Google Sheets](https://support.google.com/docs/answer/3094286?hl=es)).

Finalizando lo referente a la construcción de la tabla de frecuencias, lo más importante a destacar es su flexibilidad y alcance frente a cualquier conjunto de datos. **Se recomienda su implementación en cada análisis**, para todas las variables, permitiendo posiblemente detectar problemáticas en las mismas o incluso sacar algunas primeras conclusiones. Además, serán necesarias para la realización de algunos tipos de análisis específicos vistos más adelante.
